name: Empresa Futuro
favicon: null
layout_spectrum: 0.36056066188029945
typography_spectrum: 0.9351086681708694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.030986373545601964
  lightness: 0.7426892691291869
  saturation: 0.4528632613364607
  rhythmicContrast: 0.09599249414168298
purpose: []
