name: Empresa Futuro
favicon: null
layout_spectrum: 0.74278
typography_spectrum: 0.99834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#362f25'
    - '#fdfdfd'
    - '#22627e'
    - '#b3b8bc'
    - '#4ba0d7'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
